# P012
# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
# The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
#
# What is the value of the first triangle number to have over five hundred divisors?


import math


def main():
    count = 1
    while True:
        tri = (count * (count + 1)) / 2
        count += 2
        if factor_cnt(tri) >= 500:
            break
    print('\n# =', tri)


def factor_cnt(n):
    if n < 2:
        return 1
    factors = 1
    max = int(math.sqrt(n))
    for i in range(2, 1000):
        if i > max:
            break
        p = 0
        while n % i == 0:
            p += 1
            n /= i
        factors *= p + 1
    return factors


if __name__ == "__main__":
    main()
